### ISSUE TITLE
Page-Liste der Bewertungen

### ISSUE THREAD

**Issue by abtom61** [abtom61/knudu#4]
Die zweite Seite soll die Seite sein, die nach dem Login angezeigt werden soll. 
Auf der Seite sollte man jeden User sehen inklusive Name und Bewertung. (In Stern Form)

**Comment by abtom61** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5b9508a3e2b5190e00c6f860/attachments/5b97d086e2b5190e00c79ab2)

**Comment by abtom61** [comment]
Bitte für die Gui die Farben aus der folgenden Seite entnehmen:
https://flatuicolors.com/palette/defo

**Comment by abtom61** [comment]
Die Liste sollte am besten mit <FlatList> gemacht werden. 
Ein sehr schönes Beispiel kann man in der App „React Native“ finden, welches im Appstore zur Verfügung steht.

**Comment by subal61** [comment]
Wäre es nicht besser wenn man zuerst auf die Seite des eigenen Profils kommt? Oder man könnte die Seite in den Einstellungen auswählen. Das wäre besser finde ich. Oder?

**Comment by subal61** [comment]
Dann bräuchten wir um die Übersicht zu bewahren noch eine Tabelle in der db für die Einstellungen der benutzer.
